import type {
  MockPassage,
  MockQuestion,
  MockQuestionOption,
  MockTest,
  MockTestSection,
  MockWritingPrompt,
} from './types'

const option = (value: string, label = value): MockQuestionOption => ({ value, label })

const buildBody = (paragraphs: string[]) => paragraphs.join('\n\n')

export const IELTS_PASSAGES: MockPassage[] = [
  {
    id: 'reading-passage-1',
    title: 'Night Shift Greenhouses',
    body: buildBody([
      'Urban farms in northern cities have begun moving key operations into insulated rooftop greenhouses. Managers claim the approach reduces transport costs and lets them deliver leafy greens within hours of harvest.',
      'The biggest challenge is energy. Heating glass structures through winter is expensive, so several teams are experimenting with thermal curtains and heat batteries charged during off-peak hours.',
      'Researchers note that productivity depends less on square footage than on consistent humidity, irrigation timing, and crop rotation. Farms that monitor those variables digitally have produced steadier yields.',
      'Critics argue the model cannot replace conventional agriculture, but supporters see it as a way to secure fresh produce for dense neighborhoods during supply disruptions.',
    ]),
  },
  {
    id: 'reading-passage-2',
    title: 'The Language of Wayfinding',
    body: buildBody([
      'Wayfinding systems in large public buildings rely on more than arrows. Designers use contrast, repetition, and spatial hierarchy to guide visitors who may not speak the local language.',
      'Hospitals present a difficult case because people are often anxious and distracted. A sign that is technically accurate can still fail if it asks the reader to process too much information at once.',
      'Some teams now test navigation systems by following first-time visitors. The resulting data has shown that floor patterns, lighting, and the position of reception desks often influence decisions before a person notices a sign.',
      'As a result, modern wayfinding projects treat architecture and communication as a single system rather than separate disciplines.',
    ]),
  },
  {
    id: 'reading-passage-3',
    title: 'Museum of Everyday Objects',
    body: buildBody([
      'A regional museum once struggled to attract visitors with its collection of historical tools. Attendance improved after curators changed the narrative from "rare artifacts" to "objects that shaped daily routines."',
      'Instead of grouping items by material, the museum reorganized displays around meals, transport, and domestic repairs. That change made it easier for visitors to compare past habits with present ones.',
      'Staff also invited residents to record memories linked to similar objects. Those recordings did not replace academic labels, but they broadened the interpretation of each exhibit.',
      'The project demonstrated that audiences often respond more strongly to familiarity than to rarity alone.',
    ]),
  },
  {
    id: 'listening-passage-1',
    title: 'Orientation Tour Notes',
    body: '',
    supportingNote:
      'Audio follows a campus orientation guide describing registration, library services, and weekly study support.',
  },
  {
    id: 'listening-passage-2',
    title: 'Project Meeting',
    body: '',
    supportingNote:
      'Audio contains a workplace discussion about deadlines, supplier issues, and presentation planning.',
  },
]

export const IELTS_TESTS: MockTest[] = [
  {
    id: 'reading-test-1',
    module: 'reading',
    title: 'Academic Reading Mock 01',
    description: 'Three passages focused on innovation, design, and public spaces.',
    overview:
      'A balanced reading mock with mixed completion and matching tasks. Strong fit for students preparing for bands 6.0 to 7.5.',
    durationMinutes: 60,
    difficulty: 'intermediate',
    featured: true,
    tag: 'Popular',
    questionCount: 12,
    sectionCount: 3,
    taskCount: 0,
    sectionIds: ['reading-1-sec-1', 'reading-1-sec-2', 'reading-1-sec-3'],
    writingPromptIds: [],
    instructions: [
      'Read each passage carefully before submitting your answers.',
      'Answers are auto-saved while the session is active.',
      'Leaving the test tab will terminate the attempt immediately.',
    ],
  },
  {
    id: 'reading-test-2',
    module: 'reading',
    title: 'Academic Reading Mock 02',
    description: 'A faster-paced set with denser headings and matching tasks.',
    overview:
      'Designed for repeat practice after at least one full reading attempt. Expect heavier skimming pressure.',
    durationMinutes: 60,
    difficulty: 'advanced',
    featured: false,
    tag: 'Timed',
    questionCount: 12,
    sectionCount: 3,
    taskCount: 0,
    sectionIds: ['reading-2-sec-1', 'reading-2-sec-2', 'reading-2-sec-3'],
    writingPromptIds: [],
    instructions: [
      'Focus on headings and evidence location.',
      'Mark uncertain answers and revisit them before submit.',
      'The mock uses strict integrity rules during active timing.',
    ],
  },
  {
    id: 'listening-test-1',
    module: 'listening',
    title: 'Listening Mock 01',
    description: 'Orientation, meeting, and discussion tasks with note completion.',
    overview:
      'A realistic listening flow with note-taking pressure and short-answer sections.',
    durationMinutes: 40,
    difficulty: 'intermediate',
    featured: true,
    tag: 'Audio Shell',
    questionCount: 10,
    sectionCount: 2,
    taskCount: 0,
    sectionIds: ['listening-1-sec-1', 'listening-1-sec-2'],
    writingPromptIds: [],
    instructions: [
      'Do not open transcripts during the session.',
      'Use the navigator to move between sections after audio progress updates.',
      'Leaving the tab ends the attempt as an integrity violation.',
    ],
  },
  {
    id: 'listening-test-2',
    module: 'listening',
    title: 'Listening Mock 02',
    description: 'A denser workplace scenario with option lists and table completion.',
    overview:
      'Useful for students who struggle with distractors and rapid detail changes.',
    durationMinutes: 40,
    difficulty: 'advanced',
    featured: false,
    tag: 'Focus',
    questionCount: 10,
    sectionCount: 2,
    taskCount: 0,
    sectionIds: ['listening-2-sec-1', 'listening-2-sec-2'],
    writingPromptIds: [],
    instructions: [
      'Expect more paraphrase and distractor language.',
      'You can review all answers before final submit.',
      'Autosave runs continuously while the exam remains active.',
    ],
  },
  {
    id: 'writing-test-1',
    module: 'writing',
    title: 'Writing Mock 01',
    description: 'Task 1 process summary plus Task 2 opinion essay.',
    overview:
      'A standard academic writing simulation with a strong time-management split between Task 1 and Task 2.',
    durationMinutes: 60,
    difficulty: 'intermediate',
    featured: true,
    tag: 'Mentor Pick',
    questionCount: 0,
    sectionCount: 0,
    taskCount: 2,
    sectionIds: [],
    writingPromptIds: ['writing-1-task-1', 'writing-1-task-2'],
    instructions: [
      'Aim for at least 150 words in Task 1 and 250 words in Task 2.',
      'Drafts are auto-saved during the session.',
      'Submit once both tasks are complete or time expires.',
    ],
  },
  {
    id: 'writing-test-2',
    module: 'writing',
    title: 'Writing Mock 02',
    description: 'Task 1 comparison chart plus problem-solution essay.',
    overview:
      'A slightly more advanced writing mock that rewards precise structure and lexical variety.',
    durationMinutes: 60,
    difficulty: 'advanced',
    featured: false,
    tag: 'Structured',
    questionCount: 0,
    sectionCount: 0,
    taskCount: 2,
    sectionIds: [],
    writingPromptIds: ['writing-2-task-1', 'writing-2-task-2'],
    instructions: [
      'Organize paragraphs before you begin drafting.',
      'Use the final minutes for grammar review and cohesion fixes.',
      'Integrity events are logged for teacher review.',
    ],
  },
]

export const IELTS_TEST_SECTIONS: MockTestSection[] = [
  {
    id: 'reading-1-sec-1',
    testId: 'reading-test-1',
    order: 1,
    title: 'Section 1: Urban agriculture',
    instructions: 'Questions 1-4 are based on Passage 1.',
    passageId: 'reading-passage-1',
    questionIds: ['rq-1', 'rq-2', 'rq-3', 'rq-4'],
  },
  {
    id: 'reading-1-sec-2',
    testId: 'reading-test-1',
    order: 2,
    title: 'Section 2: Navigation systems',
    instructions: 'Questions 5-8 use matching and summary completion tasks.',
    passageId: 'reading-passage-2',
    questionIds: ['rq-5', 'rq-6', 'rq-7', 'rq-8'],
  },
  {
    id: 'reading-1-sec-3',
    testId: 'reading-test-1',
    order: 3,
    title: 'Section 3: Museum narratives',
    instructions: 'Questions 9-12 cover information matching and short answers.',
    passageId: 'reading-passage-3',
    questionIds: ['rq-9', 'rq-10', 'rq-11', 'rq-12'],
  },
  {
    id: 'reading-2-sec-1',
    testId: 'reading-test-2',
    order: 1,
    title: 'Section 1: Workspaces and focus',
    instructions: 'Questions 1-4 measure rapid evidence location.',
    passageId: 'reading-passage-2',
    questionIds: ['rq2-1', 'rq2-2', 'rq2-3', 'rq2-4'],
  },
  {
    id: 'reading-2-sec-2',
    testId: 'reading-test-2',
    order: 2,
    title: 'Section 2: Public collections',
    instructions: 'Questions 5-8 combine summary and table completion.',
    passageId: 'reading-passage-3',
    questionIds: ['rq2-5', 'rq2-6', 'rq2-7', 'rq2-8'],
  },
  {
    id: 'reading-2-sec-3',
    testId: 'reading-test-2',
    order: 3,
    title: 'Section 3: Controlled environments',
    instructions: 'Questions 9-12 require close reading across viewpoints.',
    passageId: 'reading-passage-1',
    questionIds: ['rq2-9', 'rq2-10', 'rq2-11', 'rq2-12'],
  },
  {
    id: 'listening-1-sec-1',
    testId: 'listening-test-1',
    order: 1,
    title: 'Section 1: Campus orientation',
    instructions: 'Complete the notes while the orientation guide speaks.',
    passageId: 'listening-passage-1',
    audioLabel: 'orientation_tour_demo.mp3',
    audioDurationSec: 480,
    transcript:
      'The guide explains that students should finalize registration by Friday, borrow laptops from the library help desk, and join the Wednesday clinic for weekly writing support.',
    questionIds: ['lq-1', 'lq-2', 'lq-3', 'lq-4', 'lq-5'],
  },
  {
    id: 'listening-1-sec-2',
    testId: 'listening-test-1',
    order: 2,
    title: 'Section 2: Project meeting',
    instructions: 'Answer questions about delays, decisions, and next actions.',
    passageId: 'listening-passage-2',
    audioLabel: 'project_meeting_demo.mp3',
    audioDurationSec: 510,
    transcript:
      'The team agrees to switch suppliers, move rehearsal to Thursday, and let Mia handle the revised budget slide after the client changed the deadline.',
    questionIds: ['lq-6', 'lq-7', 'lq-8', 'lq-9', 'lq-10'],
  },
  {
    id: 'listening-2-sec-1',
    testId: 'listening-test-2',
    order: 1,
    title: 'Section 1: Event logistics',
    instructions: 'Listen for option lists and practical constraints.',
    passageId: 'listening-passage-1',
    audioLabel: 'event_logistics_demo.mp3',
    audioDurationSec: 500,
    transcript:
      'The planner mentions the Riverside Hall, a backup projector, volunteer check-in at 8:15, and a late change to the catering order.',
    questionIds: ['lq2-1', 'lq2-2', 'lq2-3', 'lq2-4', 'lq2-5'],
  },
  {
    id: 'listening-2-sec-2',
    testId: 'listening-test-2',
    order: 2,
    title: 'Section 2: Research briefing',
    instructions: 'Complete a table and short answers from a research update.',
    passageId: 'listening-passage-2',
    audioLabel: 'research_briefing_demo.mp3',
    audioDurationSec: 540,
    transcript:
      'The speaker highlights a six-week pilot, lower morning attendance, two equipment faults, and a recommendation to keep the trial in one building before scaling.',
    questionIds: ['lq2-6', 'lq2-7', 'lq2-8', 'lq2-9', 'lq2-10'],
  },
]

export const IELTS_WRITING_PROMPTS: MockWritingPrompt[] = [
  {
    id: 'writing-1-task-1',
    testId: 'writing-test-1',
    order: 1,
    taskLabel: 'Task 1',
    title: 'Process diagram',
    prompt:
      'The diagram below shows how recycled paper is produced from used paper. Summarize the information by selecting and reporting the main features.',
    guidance: 'Select the major stages and compare the start and end of the process clearly.',
    minWords: 150,
    chartSummary:
      'The process includes collection, sorting, pulping, cleaning, pressing, and drying before paper is ready for reuse.',
  },
  {
    id: 'writing-1-task-2',
    testId: 'writing-test-1',
    order: 2,
    taskLabel: 'Task 2',
    title: 'Opinion essay',
    prompt:
      'Some people believe universities should focus only on academic subjects, while others think practical skills are equally important. Discuss both views and give your opinion.',
    guidance: 'State a clear position and support it with relevant examples.',
    minWords: 250,
  },
  {
    id: 'writing-2-task-1',
    testId: 'writing-test-2',
    order: 1,
    taskLabel: 'Task 1',
    title: 'Comparative chart',
    prompt:
      'The chart compares the percentage of commuters using four types of transport in one city in 2005 and 2025. Summarize the information by selecting and reporting the main features.',
    guidance: 'Identify overall trends first, then contrast the categories.',
    minWords: 150,
    chartSummary:
      'Private car use falls over time, while public transport and cycling both rise. Walking remains stable.',
  },
  {
    id: 'writing-2-task-2',
    testId: 'writing-test-2',
    order: 2,
    taskLabel: 'Task 2',
    title: 'Problem-solution essay',
    prompt:
      'Many cities are experiencing a shortage of affordable housing. What problems does this cause, and what measures could be taken to solve them?',
    guidance: 'Balance the essay between causes, consequences, and realistic solutions.',
    minWords: 250,
  },
]

export const IELTS_QUESTIONS: MockQuestion[] = [
  {
    id: 'rq-1',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-1',
    module: 'reading',
    order: 1,
    number: 1,
    type: 'multiple_choice',
    prompt: 'What is one benefit claimed for rooftop greenhouses?',
    options: [
      option('They reduce delivery time'),
      option('They require no heating'),
      option('They fully replace farms'),
      option('They increase land prices'),
    ],
    points: 1,
    correctAnswer: 'They reduce delivery time',
    explanation: 'The passage says produce can be delivered within hours of harvest.',
  },
  {
    id: 'rq-2',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-1',
    module: 'reading',
    order: 2,
    number: 2,
    type: 'true_false_not_given',
    prompt: 'Heat batteries are charged only during daytime.',
    options: [option('True'), option('False'), option('Not Given')],
    points: 1,
    correctAnswer: 'False',
    explanation: 'They are charged during off-peak hours, not specifically daytime.',
  },
  {
    id: 'rq-3',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-1',
    module: 'reading',
    order: 3,
    number: 3,
    type: 'short_answer',
    prompt: 'Which variable, besides irrigation timing, is monitored digitally for steadier yields?',
    placeholder: 'Type one or two words',
    points: 1,
    correctAnswer: 'humidity',
    explanation: 'The passage names humidity, irrigation timing, and crop rotation.',
  },
  {
    id: 'rq-4',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-1',
    module: 'reading',
    order: 4,
    number: 4,
    type: 'sentence_completion',
    prompt: 'Supporters believe rooftop farming can help during supply ____.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'disruptions',
    explanation: 'The final paragraph mentions supply disruptions.',
  },
  {
    id: 'rq-5',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-2',
    module: 'reading',
    order: 5,
    number: 5,
    type: 'matching_headings',
    prompt: 'Match the heading to each idea.',
    options: [
      option('Reducing mental effort'),
      option('Design beyond signage'),
      option('Testing by observation'),
    ],
    matchLabels: ['Paragraph B', 'Paragraph C'],
    points: 2,
    correctAnswer: {
      'Paragraph B': 'Reducing mental effort',
      'Paragraph C': 'Testing by observation',
    },
    explanation: 'Paragraph B is about anxious hospital visitors; paragraph C describes testing with first-time visitors.',
  },
  {
    id: 'rq-6',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-2',
    module: 'reading',
    order: 6,
    number: 6,
    type: 'summary_completion',
    prompt: 'Complete the summary with NO MORE THAN TWO WORDS.',
    matchLabels: ['Blank 1', 'Blank 2'],
    points: 2,
    correctAnswer: {
      'Blank 1': 'spatial hierarchy',
      'Blank 2': 'reception desks',
    },
    explanation: 'Both phrases appear in the description of design choices.',
  },
  {
    id: 'rq-7',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-2',
    module: 'reading',
    order: 7,
    number: 7,
    type: 'table_completion',
    prompt: 'Complete the table below.',
    tableRows: ['Building type', 'Testing method'],
    points: 2,
    correctAnswer: {
      'Building type': 'hospitals',
      'Testing method': 'first-time visitors',
    },
    explanation: 'Both items are stated directly.',
  },
  {
    id: 'rq-8',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-2',
    module: 'reading',
    order: 8,
    number: 8,
    type: 'multiple_choice',
    prompt: 'Modern wayfinding projects combine architecture with what?',
    options: [
      option('Lighting budgets'),
      option('Retail planning'),
      option('communication'),
      option('security software'),
    ],
    points: 1,
    correctAnswer: 'communication',
    explanation: 'The final paragraph frames architecture and communication as one system.',
  },
  {
    id: 'rq-9',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-3',
    module: 'reading',
    order: 9,
    number: 9,
    type: 'matching_information',
    prompt: 'Match each statement to the correct focus.',
    options: [option('Meals'), option('Transport'), option('Domestic repairs')],
    matchLabels: ['Display A', 'Display B'],
    points: 2,
    correctAnswer: {
      'Display A': 'Meals',
      'Display B': 'Domestic repairs',
    },
    explanation: 'The museum reorganized objects around daily routines such as meals and repairs.',
  },
  {
    id: 'rq-10',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-3',
    module: 'reading',
    order: 10,
    number: 10,
    type: 'short_answer',
    prompt: 'What did residents record to broaden interpretation?',
    placeholder: 'One or two words',
    points: 1,
    correctAnswer: 'memories',
    explanation: 'Residents recorded memories linked to the objects.',
  },
  {
    id: 'rq-11',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-3',
    module: 'reading',
    order: 11,
    number: 11,
    type: 'sentence_completion',
    prompt: 'The museum found that visitors often respond strongly to ____.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'familiarity',
    explanation: 'The last paragraph says familiarity often matters more than rarity.',
  },
  {
    id: 'rq-12',
    testId: 'reading-test-1',
    sectionId: 'reading-1-sec-3',
    module: 'reading',
    order: 12,
    number: 12,
    type: 'true_false_not_given',
    prompt: 'Academic labels were removed after residents added recordings.',
    options: [option('True'), option('False'), option('Not Given')],
    points: 1,
    correctAnswer: 'False',
    explanation: 'The recordings did not replace academic labels.',
  },
  {
    id: 'rq2-1',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-1',
    module: 'reading',
    order: 1,
    number: 1,
    type: 'multiple_choice',
    prompt: 'Which design element can influence visitors before signs do?',
    options: [option('Floor patterns'), option('Roof height'), option('Ticket price'), option('Music')],
    points: 1,
    correctAnswer: 'Floor patterns',
    explanation: 'The passage says floor patterns can shape decisions before a sign is noticed.',
  },
  {
    id: 'rq2-2',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-1',
    module: 'reading',
    order: 2,
    number: 2,
    type: 'true_false_not_given',
    prompt: 'Wayfinding systems only use written arrows.',
    options: [option('True'), option('False'), option('Not Given')],
    points: 1,
    correctAnswer: 'False',
    explanation: 'The first paragraph explicitly says they rely on more than arrows.',
  },
  {
    id: 'rq2-3',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-1',
    module: 'reading',
    order: 3,
    number: 3,
    type: 'sentence_completion',
    prompt: 'Hospital visitors may fail to read signs because they are anxious and ____.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'distracted',
    explanation: 'Both adjectives are given in the passage.',
  },
  {
    id: 'rq2-4',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-1',
    module: 'reading',
    order: 4,
    number: 4,
    type: 'short_answer',
    prompt: 'What kind of visitors are often followed in tests?',
    placeholder: 'One or two words',
    points: 1,
    correctAnswer: 'first-time visitors',
    explanation: 'Testing follows first-time visitors.',
  },
  {
    id: 'rq2-5',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-2',
    module: 'reading',
    order: 5,
    number: 5,
    type: 'summary_completion',
    prompt: 'Complete the summary.',
    matchLabels: ['Blank 1', 'Blank 2'],
    points: 2,
    correctAnswer: {
      'Blank 1': 'daily routines',
      'Blank 2': 'present ones',
    },
    explanation: 'The museum reframed objects around daily routines and present comparisons.',
  },
  {
    id: 'rq2-6',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-2',
    module: 'reading',
    order: 6,
    number: 6,
    type: 'table_completion',
    prompt: 'Complete the table.',
    tableRows: ['Old structure', 'New structure'],
    points: 2,
    correctAnswer: {
      'Old structure': 'material',
      'New structure': 'meals',
    },
    explanation: 'The museum moved from material groupings to routines such as meals.',
  },
  {
    id: 'rq2-7',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-2',
    module: 'reading',
    order: 7,
    number: 7,
    type: 'multiple_choice',
    prompt: 'What broadened interpretation of exhibits?',
    options: [option('Academic lectures'), option('Resident recordings'), option('Rare coins'), option('Digital maps')],
    points: 1,
    correctAnswer: 'Resident recordings',
    explanation: 'Residents recorded memories linked to objects.',
  },
  {
    id: 'rq2-8',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-2',
    module: 'reading',
    order: 8,
    number: 8,
    type: 'true_false_not_given',
    prompt: 'Attendance improved before the museum changed its narrative.',
    options: [option('True'), option('False'), option('Not Given')],
    points: 1,
    correctAnswer: 'False',
    explanation: 'Attendance improved after the narrative changed.',
  },
  {
    id: 'rq2-9',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-3',
    module: 'reading',
    order: 9,
    number: 9,
    type: 'matching_information',
    prompt: 'Match the detail to the factor.',
    options: [option('Humidity'), option('Crop rotation'), option('Transport costs')],
    matchLabels: ['Factor A', 'Factor B'],
    points: 2,
    correctAnswer: {
      'Factor A': 'Humidity',
      'Factor B': 'Transport costs',
    },
    explanation: 'Both factors are named in the first and third paragraphs.',
  },
  {
    id: 'rq2-10',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-3',
    module: 'reading',
    order: 10,
    number: 10,
    type: 'sentence_completion',
    prompt: 'Heating glass structures in winter is described as ____.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'expensive',
    explanation: 'The passage directly calls it expensive.',
  },
  {
    id: 'rq2-11',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-3',
    module: 'reading',
    order: 11,
    number: 11,
    type: 'short_answer',
    prompt: 'What is used alongside thermal curtains to manage energy?',
    placeholder: 'Two words',
    points: 1,
    correctAnswer: 'heat batteries',
    explanation: 'Thermal curtains and heat batteries are mentioned together.',
  },
  {
    id: 'rq2-12',
    testId: 'reading-test-2',
    sectionId: 'reading-2-sec-3',
    module: 'reading',
    order: 12,
    number: 12,
    type: 'true_false_not_given',
    prompt: 'Supporters say rooftop farms are enough to replace all agriculture.',
    options: [option('True'), option('False'), option('Not Given')],
    points: 1,
    correctAnswer: 'False',
    explanation: 'Critics argue they cannot replace conventional agriculture.',
  },
  {
    id: 'lq-1',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-1',
    module: 'listening',
    order: 1,
    number: 1,
    type: 'note_completion',
    prompt: 'Registration must be completed by ____.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'Friday',
  },
  {
    id: 'lq-2',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-1',
    module: 'listening',
    order: 2,
    number: 2,
    type: 'table_completion',
    prompt: 'Complete the support table.',
    tableRows: ['Loan item', 'Support session day'],
    points: 2,
    correctAnswer: {
      'Loan item': 'laptops',
      'Support session day': 'Wednesday',
    },
  },
  {
    id: 'lq-3',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-1',
    module: 'listening',
    order: 3,
    number: 3,
    type: 'multiple_choice',
    prompt: 'Where can students borrow the devices?',
    options: [
      option('Reception desk'),
      option('Library help desk'),
      option('Writing clinic'),
      option('Main office'),
    ],
    points: 1,
    correctAnswer: 'Library help desk',
  },
  {
    id: 'lq-4',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-1',
    module: 'listening',
    order: 4,
    number: 4,
    type: 'sentence_completion',
    prompt: 'The weekly clinic supports ____ practice.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'writing',
  },
  {
    id: 'lq-5',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-1',
    module: 'listening',
    order: 5,
    number: 5,
    type: 'short_answer',
    prompt: 'How often does the clinic run?',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'weekly',
  },
  {
    id: 'lq-6',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-2',
    module: 'listening',
    order: 6,
    number: 6,
    type: 'list_of_options',
    prompt: 'Which supplier decision did the team make?',
    options: [
      option('Keep the existing supplier'),
      option('Switch suppliers'),
      option('Delay the order'),
      option('Split the contract'),
    ],
    points: 1,
    correctAnswer: 'Switch suppliers',
  },
  {
    id: 'lq-7',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-2',
    module: 'listening',
    order: 7,
    number: 7,
    type: 'note_completion',
    prompt: 'The rehearsal was moved to ____.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'Thursday',
  },
  {
    id: 'lq-8',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-2',
    module: 'listening',
    order: 8,
    number: 8,
    type: 'multiple_choice',
    prompt: 'Who will handle the revised budget slide?',
    options: [option('Mia'), option('Alex'), option('Ravi'), option('No one')],
    points: 1,
    correctAnswer: 'Mia',
  },
  {
    id: 'lq-9',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-2',
    module: 'listening',
    order: 9,
    number: 9,
    type: 'sentence_completion',
    prompt: 'The client changed the ____.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'deadline',
  },
  {
    id: 'lq-10',
    testId: 'listening-test-1',
    sectionId: 'listening-1-sec-2',
    module: 'listening',
    order: 10,
    number: 10,
    type: 'short_answer',
    prompt: 'What slide was revised?',
    placeholder: 'Two words',
    points: 1,
    correctAnswer: 'budget slide',
  },
  {
    id: 'lq2-1',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-1',
    module: 'listening',
    order: 1,
    number: 1,
    type: 'list_of_options',
    prompt: 'Which venue was chosen?',
    options: [
      option('Central Atrium'),
      option('Riverside Hall'),
      option('South Gallery'),
      option('Harbor Studio'),
    ],
    points: 1,
    correctAnswer: 'Riverside Hall',
  },
  {
    id: 'lq2-2',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-1',
    module: 'listening',
    order: 2,
    number: 2,
    type: 'note_completion',
    prompt: 'Volunteer check-in starts at ____.',
    placeholder: 'Time',
    points: 1,
    correctAnswer: '8:15',
  },
  {
    id: 'lq2-3',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-1',
    module: 'listening',
    order: 3,
    number: 3,
    type: 'multiple_choice',
    prompt: 'What backup equipment was mentioned?',
    options: [
      option('Extra speakers'),
      option('A backup projector'),
      option('Spare microphones'),
      option('Portable lights'),
    ],
    points: 1,
    correctAnswer: 'A backup projector',
  },
  {
    id: 'lq2-4',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-1',
    module: 'listening',
    order: 4,
    number: 4,
    type: 'sentence_completion',
    prompt: 'The catering order was changed at the ____ minute.',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'late',
  },
  {
    id: 'lq2-5',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-1',
    module: 'listening',
    order: 5,
    number: 5,
    type: 'short_answer',
    prompt: 'What kind of order was changed?',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'catering',
  },
  {
    id: 'lq2-6',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-2',
    module: 'listening',
    order: 6,
    number: 6,
    type: 'table_completion',
    prompt: 'Complete the pilot summary.',
    tableRows: ['Pilot length', 'Attendance problem'],
    points: 2,
    correctAnswer: {
      'Pilot length': 'six-week',
      'Attendance problem': 'morning attendance',
    },
  },
  {
    id: 'lq2-7',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-2',
    module: 'listening',
    order: 7,
    number: 7,
    type: 'note_completion',
    prompt: 'There were ____ equipment faults.',
    placeholder: 'Number',
    points: 1,
    correctAnswer: 'two',
  },
  {
    id: 'lq2-8',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-2',
    module: 'listening',
    order: 8,
    number: 8,
    type: 'multiple_choice',
    prompt: 'What was recommended before scaling?',
    options: [
      option('Add more teams'),
      option('Move to one building first'),
      option('Buy more equipment'),
      option('Pause the trial'),
    ],
    points: 1,
    correctAnswer: 'Move to one building first',
  },
  {
    id: 'lq2-9',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-2',
    module: 'listening',
    order: 9,
    number: 9,
    type: 'short_answer',
    prompt: 'What kind of attendance was lower?',
    placeholder: 'One word',
    points: 1,
    correctAnswer: 'morning',
  },
  {
    id: 'lq2-10',
    testId: 'listening-test-2',
    sectionId: 'listening-2-sec-2',
    module: 'listening',
    order: 10,
    number: 10,
    type: 'sentence_completion',
    prompt: 'The briefing described a ____ pilot.',
    placeholder: 'One phrase',
    points: 1,
    correctAnswer: 'six-week',
  },
]
