"""initial

Revision ID: 027ebca4a96b
Revises: 
Create Date: 2026-04-11 02:30:14.842392

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '027ebca4a96b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_lesson_categories_slug')),
    sa.UniqueConstraint('title', name=op.f('uq_lesson_categories_title'))
    )
    op.create_table('listening_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('voice_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_tests'))
    )
    op.create_table('reading_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_tests'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher', 'accountant', 'student', 'user', name='role_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('writing_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_tests'))
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_admin_audit_logs_admin_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_user_id'), 'admin_audit_logs', ['admin_user_id'], unique=False)
    op.create_table('confirm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_confirm_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confirm_tokens'))
    )
    op.create_index(op.f('ix_confirm_tokens_token_hash'), 'confirm_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_confirm_tokens_user_id'), 'confirm_tokens', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('video_link', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lesson_categories.id'], name=op.f('fk_lessons_category_id_lesson_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_category_id'), 'lessons', ['category_id'], unique=False)
    op.create_table('listening_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listening_test_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_reason', sa.Enum('completed', 'left', 'time_is_up', name='finish_reason_enum', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listening_test_id'], ['listening_tests.id'], name=op.f('fk_listening_exams_listening_test_id_listening_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_listening_exams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_exams'))
    )
    op.create_index(op.f('ix_listening_exams_listening_test_id'), 'listening_exams', ['listening_test_id'], unique=False)
    op.create_index(op.f('ix_listening_exams_user_id'), 'listening_exams', ['user_id'], unique=False)
    op.create_table('listening_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['listening_tests.id'], name=op.f('fk_listening_parts_test_id_listening_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_parts')),
    sa.UniqueConstraint('test_id', 'order', name='uq_listening_part_order')
    )
    op.create_index('ix_listening_part_test_order', 'listening_parts', ['test_id', 'order'], unique=False)
    op.create_index(op.f('ix_listening_parts_test_id'), 'listening_parts', ['test_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('reading_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_test_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_reason', sa.Enum('completed', 'left', 'time_is_up', name='finish_reason_enum', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reading_test_id'], ['reading_tests.id'], name=op.f('fk_reading_exams_reading_test_id_reading_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_exams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_exams'))
    )
    op.create_index(op.f('ix_reading_exams_reading_test_id'), 'reading_exams', ['reading_test_id'], unique=False)
    op.create_index(op.f('ix_reading_exams_user_id'), 'reading_exams', ['user_id'], unique=False)
    op.create_table('reading_passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('passage_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['reading_tests.id'], name=op.f('fk_reading_passages_test_id_reading_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_passages')),
    sa.UniqueConstraint('test_id', 'passage_number', name='uq_reading_passage_order')
    )
    op.create_index('ix_reading_passage_test_passage', 'reading_passages', ['test_id', 'passage_number'], unique=False)
    op.create_index(op.f('ix_reading_passages_test_id'), 'reading_passages', ['test_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_tests_taken', sa.Integer(), nullable=False),
    sa.Column('average_band_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('best_band_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('total_study_time_seconds', sa.Integer(), nullable=False),
    sa.Column('last_test_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_analytics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_analytics')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_analytics_user_id'))
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('native_language', sa.String(length=50), nullable=False),
    sa.Column('target_band_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('band_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('test_type', sa.Enum('reading', 'listening', 'writing', 'speaking', name='progress_test_type_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_progress'))
    )
    op.create_index('ix_progress_user_test_date', 'user_progress', ['user_id', 'test_date'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('writing_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('writing_test_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_reason', sa.Enum('completed', 'left', 'time_is_up', name='finish_reason_enum', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_writing_exams_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['writing_test_id'], ['writing_tests.id'], name=op.f('fk_writing_exams_writing_test_id_writing_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_exams'))
    )
    op.create_index(op.f('ix_writing_exams_user_id'), 'writing_exams', ['user_id'], unique=False)
    op.create_index(op.f('ix_writing_exams_writing_test_id'), 'writing_exams', ['writing_test_id'], unique=False)
    op.create_table('writing_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('file_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['writing_tests.id'], name=op.f('fk_writing_parts_test_id_writing_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_parts')),
    sa.UniqueConstraint('test_id', 'order', name='uq_writing_part_order')
    )
    op.create_index(op.f('ix_writing_parts_test_id'), 'writing_parts', ['test_id'], unique=False)
    op.create_table('listening_question_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('block_type', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('table_completion', sa.Text(), nullable=True),
    sa.Column('table_json', sa.JSON(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'done', 'failed', name='parse_status_enum', native_enum=False), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['listening_parts.id'], name=op.f('fk_listening_question_blocks_part_id_listening_parts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_question_blocks')),
    sa.UniqueConstraint('part_id', 'order', name='uq_listening_block_order')
    )
    op.create_index('ix_listening_block_part_order', 'listening_question_blocks', ['part_id', 'order'], unique=False)
    op.create_index(op.f('ix_listening_question_blocks_part_id'), 'listening_question_blocks', ['part_id'], unique=False)
    op.create_table('reading_question_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('block_type', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_heading', sa.String(length=255), nullable=True),
    sa.Column('list_of_headings', sa.Text(), nullable=True),
    sa.Column('table_completion', sa.Text(), nullable=True),
    sa.Column('flow_chart_completion', sa.Text(), nullable=True),
    sa.Column('table_json', sa.JSON(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'done', 'failed', name='parse_status_enum', native_enum=False), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['reading_passages.id'], name=op.f('fk_reading_question_blocks_passage_id_reading_passages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_question_blocks')),
    sa.UniqueConstraint('passage_id', 'order', name='uq_reading_block_order')
    )
    op.create_index('ix_reading_block_passage_order', 'reading_question_blocks', ['passage_id', 'order'], unique=False)
    op.create_index(op.f('ix_reading_question_blocks_passage_id'), 'reading_question_blocks', ['passage_id'], unique=False)
    op.create_table('writing_exam_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('essay', sa.Text(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('corrections', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['writing_exams.id'], name=op.f('fk_writing_exam_parts_exam_id_writing_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['writing_parts.id'], name=op.f('fk_writing_exam_parts_part_id_writing_parts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_writing_exam_parts')),
    sa.UniqueConstraint('exam_id', 'part_id', name='uq_writing_exam_part')
    )
    op.create_index(op.f('ix_writing_exam_parts_exam_id'), 'writing_exam_parts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_writing_exam_parts_part_id'), 'writing_exam_parts', ['part_id'], unique=False)
    op.create_table('listening_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_block_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_block_id'], ['listening_question_blocks.id'], name=op.f('fk_listening_questions_question_block_id_listening_question_blocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_questions')),
    sa.UniqueConstraint('question_block_id', 'order', name='uq_listening_question_order')
    )
    op.create_index('ix_listening_question_block_order', 'listening_questions', ['question_block_id', 'order'], unique=False)
    op.create_index(op.f('ix_listening_questions_question_block_id'), 'listening_questions', ['question_block_id'], unique=False)
    op.create_table('reading_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_block_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_block_id'], ['reading_question_blocks.id'], name=op.f('fk_reading_questions_question_block_id_reading_question_blocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_questions')),
    sa.UniqueConstraint('question_block_id', 'order', name='uq_reading_question_order')
    )
    op.create_index('ix_reading_question_block_order', 'reading_questions', ['question_block_id', 'order'], unique=False)
    op.create_index(op.f('ix_reading_questions_question_block_id'), 'reading_questions', ['question_block_id'], unique=False)
    op.create_table('listening_exam_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['listening_exams.id'], name=op.f('fk_listening_exam_question_answers_exam_id_listening_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['listening_questions.id'], name=op.f('fk_listening_exam_question_answers_question_id_listening_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_exam_question_answers')),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_listening_exam_question_answer')
    )
    op.create_index(op.f('ix_listening_exam_question_answers_exam_id'), 'listening_exam_question_answers', ['exam_id'], unique=False)
    op.create_index(op.f('ix_listening_exam_question_answers_question_id'), 'listening_exam_question_answers', ['question_id'], unique=False)
    op.create_table('listening_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['listening_questions.id'], name=op.f('fk_listening_question_answers_question_id_listening_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_question_answers'))
    )
    op.create_index(op.f('ix_listening_question_answers_question_id'), 'listening_question_answers', ['question_id'], unique=False)
    op.create_table('listening_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['listening_questions.id'], name=op.f('fk_listening_question_options_question_id_listening_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_question_options'))
    )
    op.create_index(op.f('ix_listening_question_options_question_id'), 'listening_question_options', ['question_id'], unique=False)
    op.create_table('reading_exam_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['reading_exams.id'], name=op.f('fk_reading_exam_question_answers_exam_id_reading_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], name=op.f('fk_reading_exam_question_answers_question_id_reading_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_exam_question_answers')),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_reading_exam_question_answer')
    )
    op.create_index(op.f('ix_reading_exam_question_answers_exam_id'), 'reading_exam_question_answers', ['exam_id'], unique=False)
    op.create_index(op.f('ix_reading_exam_question_answers_question_id'), 'reading_exam_question_answers', ['question_id'], unique=False)
    op.create_table('reading_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], name=op.f('fk_reading_question_answers_question_id_reading_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_question_answers'))
    )
    op.create_index(op.f('ix_reading_question_answers_question_id'), 'reading_question_answers', ['question_id'], unique=False)
    op.create_table('reading_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], name=op.f('fk_reading_question_options_question_id_reading_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_question_options'))
    )
    op.create_index(op.f('ix_reading_question_options_question_id'), 'reading_question_options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_question_options_question_id'), table_name='reading_question_options')
    op.drop_table('reading_question_options')
    op.drop_index(op.f('ix_reading_question_answers_question_id'), table_name='reading_question_answers')
    op.drop_table('reading_question_answers')
    op.drop_index(op.f('ix_reading_exam_question_answers_question_id'), table_name='reading_exam_question_answers')
    op.drop_index(op.f('ix_reading_exam_question_answers_exam_id'), table_name='reading_exam_question_answers')
    op.drop_table('reading_exam_question_answers')
    op.drop_index(op.f('ix_listening_question_options_question_id'), table_name='listening_question_options')
    op.drop_table('listening_question_options')
    op.drop_index(op.f('ix_listening_question_answers_question_id'), table_name='listening_question_answers')
    op.drop_table('listening_question_answers')
    op.drop_index(op.f('ix_listening_exam_question_answers_question_id'), table_name='listening_exam_question_answers')
    op.drop_index(op.f('ix_listening_exam_question_answers_exam_id'), table_name='listening_exam_question_answers')
    op.drop_table('listening_exam_question_answers')
    op.drop_index(op.f('ix_reading_questions_question_block_id'), table_name='reading_questions')
    op.drop_index('ix_reading_question_block_order', table_name='reading_questions')
    op.drop_table('reading_questions')
    op.drop_index(op.f('ix_listening_questions_question_block_id'), table_name='listening_questions')
    op.drop_index('ix_listening_question_block_order', table_name='listening_questions')
    op.drop_table('listening_questions')
    op.drop_index(op.f('ix_writing_exam_parts_part_id'), table_name='writing_exam_parts')
    op.drop_index(op.f('ix_writing_exam_parts_exam_id'), table_name='writing_exam_parts')
    op.drop_table('writing_exam_parts')
    op.drop_index(op.f('ix_reading_question_blocks_passage_id'), table_name='reading_question_blocks')
    op.drop_index('ix_reading_block_passage_order', table_name='reading_question_blocks')
    op.drop_table('reading_question_blocks')
    op.drop_index(op.f('ix_listening_question_blocks_part_id'), table_name='listening_question_blocks')
    op.drop_index('ix_listening_block_part_order', table_name='listening_question_blocks')
    op.drop_table('listening_question_blocks')
    op.drop_index(op.f('ix_writing_parts_test_id'), table_name='writing_parts')
    op.drop_table('writing_parts')
    op.drop_index(op.f('ix_writing_exams_writing_test_id'), table_name='writing_exams')
    op.drop_index(op.f('ix_writing_exams_user_id'), table_name='writing_exams')
    op.drop_table('writing_exams')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index('ix_progress_user_test_date', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_table('user_profiles')
    op.drop_table('user_analytics')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_reading_passages_test_id'), table_name='reading_passages')
    op.drop_index('ix_reading_passage_test_passage', table_name='reading_passages')
    op.drop_table('reading_passages')
    op.drop_index(op.f('ix_reading_exams_user_id'), table_name='reading_exams')
    op.drop_index(op.f('ix_reading_exams_reading_test_id'), table_name='reading_exams')
    op.drop_table('reading_exams')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_listening_parts_test_id'), table_name='listening_parts')
    op.drop_index('ix_listening_part_test_order', table_name='listening_parts')
    op.drop_table('listening_parts')
    op.drop_index(op.f('ix_listening_exams_user_id'), table_name='listening_exams')
    op.drop_index(op.f('ix_listening_exams_listening_test_id'), table_name='listening_exams')
    op.drop_table('listening_exams')
    op.drop_index(op.f('ix_lessons_category_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_confirm_tokens_user_id'), table_name='confirm_tokens')
    op.drop_index(op.f('ix_confirm_tokens_token_hash'), table_name='confirm_tokens')
    op.drop_table('confirm_tokens')
    op.drop_index(op.f('ix_admin_audit_logs_admin_user_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_table('writing_tests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reading_tests')
    op.drop_table('listening_tests')
    op.drop_table('lesson_categories')
    # ### end Alembic commands ###
